Accessing/chanaging specific elements rows, cols, etc

In [50]:
import numpy as np
a=np.array ([[1,2,3,4,5,6,7],[9,8,7,6,5,4,3]])
print(a)

[[1 2 3 4 5 6 7]
 [9 8 7 6 5 4 3]]


In [51]:
#get a specific element:[r,c]
a[1,-5]

7

In [52]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [53]:
#get a specific col
a[:,2]

array([3, 7])

In [54]:
#getting a litter more fancy [startindex:endindex:stepsize]
a[0,:6:2]
a[0,:6:-2]
a[0,:-2:2]

array([1, 3, 5])

In [55]:
#change something in row
a[1,5]=30
print(a)

[[ 1  2  3  4  5  6  7]
 [ 9  8  7  6  5 30  3]]


In [56]:
#change something in col
a[:,2]=7
print(a)

[[ 1  2  7  4  5  6  7]
 [ 9  8  7  6  5 30  3]]
