#my first notebook

In [18]:
import numpy as np
a=np.array([1,3,5], dtype =np.int16)
b=np.array([3,4,5])
print(a*b)

[ 3 12 25]


In [19]:
a=np.array([1,3,5])
print(a)

[1 3 5]


In [20]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])# 2D array
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
#get dimensions
b.ndim

2

In [22]:
#get shape
a.shape  #vector
b.shape

(2, 4)

In [23]:
#get type
a.dtype

dtype('int32')

In [24]:
a.dtype

dtype('int32')

In [25]:
#get size
a.itemsize

4

In [26]:
#get total size
a.size
a.nbytes

12